// Package protocol defines the versioned control model shared by every
// HopDrop platform. Transport is HTTPS; file bytes are streamed as HTTP request
// bodies and are therefore deliberately not represented by custom frames.
package protocol

import (
	"encoding/hex"
	"errors"
	"fmt"
	"path"
	"strings"
)

func ValidateFingerprint(value string) error {
	raw, err := hex.DecodeString(value)
	if err != nil || len(raw) != 32 || value != strings.ToLower(value) {
		return errors.New("protocol: fingerprint must be 64 lowercase hexadecimal characters")
	}
	return nil
}

const (
	// ProtocolVersion is bumped whenever the HTTP contract changes.
	ProtocolVersion = 1

	// Limits are enforced before an offer reaches the user and again for every
	// upload. They keep a peer from understating an offer and exhausting disk.
	MaxFilesPerTransfer = 10_000
	MaxFileSize         = int64(16 << 30) // 16 GiB
	MaxTransferSize     = int64(1 << 40)  // 1 TiB
)

// Platform identifies the UI/runtime hosting the shared Go core.
type Platform string

const (
	PlatformIOS     Platform = "ios"
	PlatformAndroid Platform = "android"
	PlatformMacOS   Platform = "macos"
	PlatformWindows Platform = "windows"
	PlatformLinux   Platform = "linux"
	PlatformCLI     Platform = "cli"
	PlatformUnknown Platform = "unknown"
)

// DeviceInfo is the identity advertised through discovery and exchanged in an
// offer. Fingerprint is the SHA-256 fingerprint of the device's Ed25519 public
// key and is verified against its TLS certificate.
type DeviceInfo struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Platform    Platform `json:"platform"`
	SyncPort    int      `json:"sync_port"`
	Fingerprint string   `json:"fingerprint,omitempty"`
}

// FileMeta is the authoritative metadata for one offered file. Later upload
// requests refer only to ID, so metadata cannot change after user approval.
type FileMeta struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	RelPath  string `json:"rel_path"`
	Size     int64  `json:"size"`
	ModUnix  int64  `json:"mod_unix"`
	MimeType string `json:"mime_type,omitempty"`
}

// Offer is shown to the receiver before any bytes are uploaded.
type Offer struct {
	Files      []FileMeta `json:"files"`
	TotalBytes int64      `json:"total_bytes"`
}

// Decision is returned by the receiver UI. A nil AcceptIDs accepts all files;
// an explicit empty slice accepts none.
type Decision struct {
	Accept    bool     `json:"accept"`
	AcceptIDs []string `json:"accept_ids,omitempty"`
	Reason    string   `json:"reason,omitempty"`
}

type TransferStatus string

const (
	StatusAccepted TransferStatus = "accepted"
	StatusRejected TransferStatus = "rejected"
	StatusComplete TransferStatus = "complete"
	StatusCanceled TransferStatus = "canceled"
)

// CreateTransferRequest starts a transfer and blocks until the receiver makes
// a decision. SessionID is generated by the sender and is unguessable.
type CreateTransferRequest struct {
	Version   int        `json:"version"`
	SessionID string     `json:"session_id"`
	Sender    DeviceInfo `json:"sender"`
	Offer     Offer      `json:"offer"`
}

type CreateTransferResponse struct {
	Version     int            `json:"version"`
	SessionID   string         `json:"session_id"`
	Status      TransferStatus `json:"status"`
	Receiver    DeviceInfo     `json:"receiver"`
	AcceptedIDs []string       `json:"accepted_ids"`
	Reason      string         `json:"reason,omitempty"`
}

// FileReceipt is returned after the receiver has durably consumed a file.
// SHA256 is lowercase hexadecimal.
type FileReceipt struct {
	ID     string `json:"id"`
	Size   int64  `json:"size"`
	SHA256 string `json:"sha256"`
}

// TransferResult is the receiver's final acknowledgement. The sender must not
// report success until this result has been received and validated.
type TransferResult struct {
	Version   int            `json:"version"`
	SessionID string         `json:"session_id"`
	Status    TransferStatus `json:"status"`
	Files     []FileReceipt  `json:"files"`
	Error     string         `json:"error,omitempty"`
}

type ErrorResponse struct {
	Error string `json:"error"`
}

// ValidateOffer rejects ambiguous or dangerous manifests and returns the
// authoritative total computed from file sizes. Wire paths always use '/'.
func ValidateOffer(offer Offer) (int64, error) {
	if len(offer.Files) == 0 {
		return 0, errors.New("protocol: offer contains no files")
	}
	if len(offer.Files) > MaxFilesPerTransfer {
		return 0, fmt.Errorf("protocol: too many files: %d", len(offer.Files))
	}
	seen := make(map[string]struct{}, len(offer.Files))
	var total int64
	for _, f := range offer.Files {
		if f.ID == "" {
			return 0, errors.New("protocol: empty file id")
		}
		if _, ok := seen[f.ID]; ok {
			return 0, fmt.Errorf("protocol: duplicate file id %q", f.ID)
		}
		seen[f.ID] = struct{}{}
		if f.Size < 0 || f.Size > MaxFileSize {
			return 0, fmt.Errorf("protocol: invalid size for %q: %d", f.ID, f.Size)
		}
		if err := ValidateRelPath(f.RelPath); err != nil {
			return 0, fmt.Errorf("protocol: file %q: %w", f.ID, err)
		}
		if f.Name == "" || strings.ContainsAny(f.Name, "/\\") {
			return 0, fmt.Errorf("protocol: invalid name for %q", f.ID)
		}
		if path.Base(f.RelPath) != f.Name {
			return 0, fmt.Errorf("protocol: name does not match rel_path for %q", f.ID)
		}
		if total > MaxTransferSize-f.Size {
			return 0, errors.New("protocol: transfer exceeds size limit")
		}
		total += f.Size
	}
	if total != offer.TotalBytes {
		return 0, fmt.Errorf("protocol: total_bytes is %d, computed %d", offer.TotalBytes, total)
	}
	return total, nil
}

// ValidateRelPath enforces the platform-neutral path syntax consumed by every
// Sink. Invalid paths are rejected instead of silently rewritten.
func ValidateRelPath(rel string) error {
	if rel == "" || strings.ContainsRune(rel, '\x00') || strings.Contains(rel, "\\") {
		return fmt.Errorf("invalid relative path %q", rel)
	}
	clean := path.Clean(rel)
	if clean != rel || clean == "." || strings.HasPrefix(clean, "/") ||
		clean == ".." || strings.HasPrefix(clean, "../") {
		return fmt.Errorf("invalid relative path %q", rel)
	}
	return nil
}

// AcceptedFiles normalizes a decision into an explicit, offer-ordered list.
func AcceptedFiles(offer Offer, decision Decision) ([]FileMeta, error) {
	if !decision.Accept {
		return nil, nil
	}
	if decision.AcceptIDs == nil {
		return append([]FileMeta(nil), offer.Files...), nil
	}
	want := make(map[string]struct{}, len(decision.AcceptIDs))
	for _, id := range decision.AcceptIDs {
		if _, duplicate := want[id]; duplicate {
			return nil, fmt.Errorf("protocol: duplicate accepted id %q", id)
		}
		want[id] = struct{}{}
	}
	out := make([]FileMeta, 0, len(want))
	for _, f := range offer.Files {
		if _, ok := want[f.ID]; ok {
			out = append(out, f)
			delete(want, f.ID)
		}
	}
	for id := range want {
		return nil, fmt.Errorf("protocol: accepted id %q was not offered", id)
	}
	return out, nil
}
