Icon = "Icon.png"
Name = "HopDrop"
ID = "com.hopdrop.desktop"
Version = "0.1.0"
Build = 1

[Details]
  Icon = "Icon.png"
  Name = "HopDrop"
  ID = "com.hopdrop.desktop"
  Version = "0.1.0"
  Build = 1
